#!/bin/bash
#
# SSH setup
# Installs the versioned ssh config (personal + professional GitHub hosts) and
# generates ONLY the personal key if it is missing. Professional private keys
# are never copied or generated by this script.

source ./scripts/utils.sh

echo_info "Configuring SSH..."

# Ensure ~/.ssh exists with correct permissions
mkdir -p ~/.ssh
chmod 700 ~/.ssh

# Install the SSH config (github.com, github-lftm, github-lftmtech)
replace "./scripts/ssh_config" ".ssh/config"
chmod 600 ~/.ssh/config

# Generate the personal key only if absent
if [ ! -f ~/.ssh/id_ed25519 ]; then
  echo_info "Create a password for your personal SSH key:"
  ssh-keygen -q -t ed25519 -o -a 100 -C "$SSH_EMAIL" -f ~/.ssh/id_ed25519
  chmod 600 ~/.ssh/id_ed25519
  chmod 644 ~/.ssh/id_ed25519.pub
else
  echo_info "Personal key ~/.ssh/id_ed25519 already exists, skipping generation."
fi

echo_warning "Professional keys (id_ed25519_lftm / id_ed25519_lftmtech) must be provided manually."
echo_warning "Use the copyssh command to copy your personal public key to the clipboard."

# Finish
echo_success "SSH configuration complete."
